import type { Metadata } from "next";
import "./globals.css";
import {geistSans, geistMono, pixelify, chicle} from "@/app/components/ui/font/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${chicle.variable} ${pixelify.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
